### ISSUE TITLE
Requests table doesn't show users request data

### ISSUE THREAD

**Issue by ChristopherHarwell** [fp-rap-build/front-end#29]
When logged in as an admin the request table doesn't display the data of users who have requests properly
![Screenshot from 2021-03-06 07-17-50](https://user-images.githubusercontent.com/45679995/110206504-13d0d700-7e4c-11eb-9a8b-b07bb0b9787f.png)

**Comment by ChristopherHarwell** [comment]
I can confirm that state does contain the user data we need but can't figure out why the data isn't displaying properly

![Screenshot from 2021-03-06 07-25-23](https://user-images.githubusercontent.com/45679995/110206673-24358180-7e4d-11eb-9246-4e7f998b9315.png)

**Comment by joeywire** [comment]
Resolved with new end point
