### ISSUE TITLE
City Filter needs a little tweaking

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#37]
Filter for city when registering an account is too strict when parsing input.  It is currently being marked as invalid with a space after the name (let's just ignore trailing whitespace instead of forbidding it)

Spokane Valley is a valid city that is not allowed, this is a city that will make many rental requests on the site so this will need to be resolved prior to going live.

**Comment by isaiah-j** [comment]
Nice catch, the filter is now accepting whitespace and trims all of the strings before a request is submitted
