### ISSUE TITLE
Address bar abbreviations

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#40]
Filter for address bar on eligibility form is not allowing the use of abbreviations such as 'N.' for North. Will prevent the ability to live on streets with abbreviations in the name. 
<img width="1440" alt="Screen Shot 2021-03-12 at 11 34 16 AM" src="https://user-images.githubusercontent.com/11794794/110989909-754ee500-8327-11eb-8c9a-48296513aa50.png">

**Comment by isaiah-j** [comment]
Updated cityName to include dashes, periods and commas
