### ISSUE TITLE
address bar apartment and unit numbers

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#41]
Address bar in eligibility form is not allowing the pound sign.  Users in apartments are not able to put their apartment number 

<img width="1440" alt="Screen Shot 2021-03-12 at 11 34 27 AM" src="https://user-images.githubusercontent.com/11794794/110990053-a62f1a00-8327-11eb-8ae7-a7fa2b895af9.png">

**Comment by isaiah-j** [comment]
Updated address to include dashes, periods and commas
