### ISSUE TITLE
Create Account Manager failing

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#42]
<img width="1440" alt="Screen Shot 2021-03-12 at 12 28 16 PM" src="https://user-images.githubusercontent.com/11794794/110995027-87805180-832e-11eb-8628-830f23a0a5c7.png">

**Comment by joeywire** [comment]
Fixed earlier this week by Isaiah - confirmed it is working on production

**Comment by iesous-kurios** [comment]
K, haven't checked it myself, but will close for now
