### ISSUE TITLE
Nav button on Mobile

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#48]
Navigation button is cut off on mobile view.

![Screenshot_20210313-195902_Chrome.jpg](https://user-images.githubusercontent.com/11794794/111056777-aa962880-8436-11eb-9f39-d5300f8cb750.jpg)

**Comment by joeywire** [comment]
Working...

**Comment by joeywire** [comment]
![image](https://user-images.githubusercontent.com/61367542/111079658-dd88fc80-84c8-11eb-8b8a-bb0a3ed25c40.png)
