### ISSUE TITLE
Request date

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#51]
Request date on dashboard shows prior day as the request date

Made 'jdude' request today, the 14th, and request date on dashboard shows the 13th. 

![Screenshot_20210314-131334_Chrome.jpg](https://user-images.githubusercontent.com/11794794/111082792-5c7d3580-84c7-11eb-9c3e-927939276182.jpg)

**Comment by joeywire** [comment]
working...

**Comment by iesous-kurios** [comment]
Looks good, closing this issue

**Comment by iesous-kurios** [comment]
Locally it is working well for me, deployed site is still one day behind, not sure if there are more changes that need to be merged for it to work on deployed site
