### ISSUE TITLE
Question Phrasing, and Intro

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#52]
Check box might not be intuitive to all users.

Consider rephrase and an Intro sentence above the check boxes:

"Please place a checkmark next to all of the statements below that are true for you and/or somebody in your household"

[ ] Been unemployed for 90+ Days

[ ] Have worked in the Food Service Industry at any time between January 1st 2020 today's date

<img width="1440" alt="Screen Shot 2021-03-14 at 3 48 43 PM" src="https://user-images.githubusercontent.com/11794794/111087155-36fb2680-84dd-11eb-91f7-598fa48405b8.png">

**Comment by isaiah-j** [comment]
Message changes to "Please place a checkmark next to all of the statements below that are true for your tenant"
if the user selects landlord.

<img width="507" alt="intro" src="https://user-images.githubusercontent.com/66272034/111111639-1959ab80-8535-11eb-9b35-0993b37743db.PNG">

**Comment by iesous-kurios** [comment]
Yes, that looks good.

**Comment by iesous-kurios** [comment]
Think this is fixed now.
