### ISSUE TITLE
New DS API

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#54]
Updated DS API isn't being utilized to more accurately predict eligibility.

**Comment by isaiah-j** [comment]
- Both of the booleans were changed to 0/1 before sending to api. 

Everything seems to be working with the zip codes. 

Testing with zip code: 16504

<img width="383" alt="16504" src="https://user-images.githubusercontent.com/66272034/111152699-6787a280-8567-11eb-8c02-78056f277ebb.PNG">

With 99206 (spokane zipcode)

<img width="355" alt="99206" src="https://user-images.githubusercontent.com/66272034/111153460-5db26f00-8568-11eb-8a09-45255971e315.PNG">

**Comment by iesous-kurios** [comment]
I had to change the 1s and 0s out of int into str representations .  (not really webs fault, it is my ds api... well, really it is fast api not behaving the way it should)

DS API with bools and 1/0 works fine on colab, but when put into python files for production the behavior changes. Not sure why.  Working with strings now just to get ds api to work.  Will troubleshoot api here and there to figure out why bools aren't working, but the main functionality of the app is most important and that is working now.
