### ISSUE TITLE
Additional Questions

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#59]
Need to know how much user is requesting in assistance

How much is owed (confirmed with Landlord)

Not sure where to add these questions.  

Perhaps they can be asked on account creation, after checking eligibility.  

Might need to be added to basic information page, not sure.

**Comment by ChristopherHarwell** [comment]
Will work on this tomorrow

**Comment by iesous-kurios** [comment]
Closing this issue, I recreated this in the project section in Users project.
