### ISSUE TITLE
SNAP eligibility

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#61]
SNAP is only showing up when both unemp and foodwrkr are true.

SNAP should instead show up with unemp is true.

foodwrkr is not a qualification for SNAP, it helps Fam Prom direct funds we received for food service workers.

**Comment by isaiah-j** [comment]
This is might be a DS issue. Are you getting the same behavior when testing the API?

**Comment by iesous-kurios** [comment]
DS API returns:

{
  "SNAP": 1,
  "CC": 0,
  "FP": 0
}

But main branch right now needs both unemployed and the food worker boxes to be checked before it displays SNAP apply

![Uploading Screen Shot 2021-03-15 at 8.09.55 PM.png…]()

**Comment by iesous-kurios** [comment]
<img width="1440" alt="Screen Shot 2021-03-15 at 8 09 59 PM" src="https://user-images.githubusercontent.com/11794794/111250592-d64a1780-85ca-11eb-904b-c29de2a11ef9.png">

**Comment by iesous-kurios** [comment]
Pretty sure I fixed this.  I messed up a button so it was accepting checkboxes on the front end but not storing it and sending it anywhere.  

Seems functional now and is being passed through to display when queried later for various dashboards
