### ISSUE TITLE
File edit

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#86]
Weird string of numbers attaches itself to document name when downloading them. 
<img width="1440" alt="Screen Shot 2021-03-21 at 10 02 16 PM" src="https://user-images.githubusercontent.com/11794794/111942763-38a28c80-8a91-11eb-9914-3f3ad37bceac.png">

**Comment by isaiah-j** [comment]
That's a UTC timestamp to keep every document unique on the aws bucket. Although I'm not sure if it cares about unique filenames, I'll look more into it

**Comment by isaiah-j** [comment]
Looks like every filename needs to be unique for AWS. I can move the string to the end of the filename to be easier to read but that's the best we can do
