### ISSUE TITLE
status change

### ISSUE THREAD

**Issue by iesous-kurios** [fp-rap-build/front-end#94]
Request status isn't changing from 'received' to 'in review' after request is opened by program manager

<img width="1440" alt="Screen Shot 2021-03-22 at 3 40 27 PM" src="https://user-images.githubusercontent.com/11794794/112067391-368a0d80-8b25-11eb-95f1-717cf02767c3.png">

**Comment by isaiah-j** [comment]
Nice catch, I submitted a PR for this
